apiVersion: extensions/v1beta1
kind : Deployment
metadata:
  name: nginx-deployment-prod
spec:
  replicas: 10
  template:
    metadata:
       labels:
         app: nginx-deployment-prod
    spec:
      containers:
      - name: nginx-deployment-prod
        image:  nginx:1.8
        ports:
        - containerPort: 80
